### ISSUE TITLE
Does it work for the register form?

### ISSUE THREAD

**Issue by jeremydouglas** [aryehraber/statamic-captcha#13]
Does this add-on work with the `register` form? I thought it did, but doesn't seem to be working now.

**Comment by aryehraber** [comment]
Hey @jeremydouglas! Unfortunately it doesn't atm... the previous version for Statamic V2 had this feature. 

At the time of upgrading the addon from Statamic V2 to V3, there wasn't a hook (event) to listen for to intercept the registration process. I haven't been following along with recent Statamic releases but perhaps this event has been added now so the feature could be added. 

If you have more info and/or are able to submit a PR, I'd be more than happy to merge it in. Otherwise, I'll see if I can find some time to look into Statamic core soon to see if an event has been added since I last looked.

**Comment by aryehraber** [comment]
Ah, looks like the event does exist: https://github.com/statamic/cms/blob/3.0/src/Events/UserRegistering.php

Will try and find some time in the coming weeks!

**Comment by jeremydouglas** [comment]
Yes, I think it's a more recent addition. Thanks!

**Comment by aryehraber** [comment]
@jeremydouglas Added support in latest release, let me know if you notice any issues!
