### ISSUE TITLE
Disable/enable captcha

### ISSUE THREAD

**Issue by lamuye** [aryehraber/statamic-captcha#54]
I'm trying to disable/enable captcha based on the user's needs but haven't got very far. I have thought of putting captcha:head and captcha tag in an if statement but it didn't work.

**Comment by aryehraber** [comment]
Hi @lamuye! 

This isn't currently possible in the way you describe. Once Captcha is installed and you've configured the forms to protect, any of those forms **must** include a successful captcha response, otherwise an error is thrown. Removing the frontend tags (` {{ captcha:head }}` and `{{ captcha }}`) will have no effect on the backend logic throwing a "captcha error".

Can you explain your use-case? What are "the user's needs" that you would want to enable/disable Captcha based on?

**Comment by lamuye** [comment]
in my case, im using toggel button to let the use chose whether they want captcha on their project or not.

**Comment by aryehraber** [comment]
Right ok, interesting! Unfortunately, I think this request is too far outside the scope of this addon tbh — it sounds very specific to your use-case.

I'm not sure how familiar you are with Statamic/Laravel's internals, but I think you could potentially try to create a custom Service Provider that registers _after_ this addon's Service Provider and conditionally disable Captcha by removing/overriding the binding that is created during initialisation ([see Captcha's binding here](https://github.com/aryehraber/statamic-captcha/blob/master/src/CaptchaServiceProvider.php#L27-L37)).

Good luck!

**Comment by aryehraber** [comment]
Hi @lamuye! Been a while but wanted to make you aware of some changes that were just released that give you more control of the verification process, in case you're still interested in this. 

As of `v1.12.0` you can create a custom invokable class that gives you the ability to bypass the verification step based on your own custom logic. You can read more about it in the [docs](https://github.com/aryehraber/statamic-captcha?tab=readme-ov-file#advanced).
